### ISSUE TITLE
Typo in the documentation: \undef instead of \gundef

### ISSUE THREAD

**Issue by dbitouze** [josephwright/etoolbox#16]
There is a typo in the documentation, page 7: the macro "[s]imilar to `\undef` but [that] acts globally" is said to be `\undef` instead of `\gundef`.

**Comment by muzimuzhi** [comment]
@dbitouze I have made a pull request (see #17 ) which fixes this issue.

And I apologize for my first two stupid commits. Sometimes newbie makes a lot of noise making his/her first pull request. Sorry for that.
