### ISSUE TITLE
46533 -> 46550 causes "Math formula deleted: Insufficient symbol fonts"

### ISSUE THREAD

**Issue by pitkling** [josephwright/etoolbox#19]
When I updated my MacTeX 2017 installation this morning via tlmgr, etoolbox was updated from 46533 to 46550. Since then, I get "Math formula deleted: Insufficient symbol fonts" errors for simple tex files like:

```latex
\documentclass{article}
\usepackage{biblatex}
\begin{document}
\end{document}
```

When I uncomment biblatex, it works. Loading mdframed instead of biblatex causes similar errors. When I revert etoolbox to 46533, everything works again.

I attached the [log file](https://github.com/josephwright/etoolbox/files/1698394/main.log) for the above example when compiling with etoolbox 46550.

**Comment by josephwright** [comment]
Ah, I see the issue: I'd not allowed for multiple tokens in the 'payloads'. Fix coming up!

**Comment by josephwright** [comment]
Temporary fix: load `etoolbox` first, then add
```latex
\makeatletter
\long\def\etb@listitem#1#2{%
  \expandafter\ifblank\expandafter{\@gobble#2}
    {}
    {\expandafter\etb@listitem@i
     \expandafter{\@secondoftwo#2}{#1}}}
\long\def\etb@listitem@i#1#2{#2{#1}}
\makeatother
```

**Comment by josephwright** [comment]
Temporary fix:
```latex
\documentclass{article}
\usepackage{etoolbox}
\makeatletter
\long\def\etb@listitem#1#2{%
  \expandafter\ifblank\expandafter{\@gobble#2}
    {}
    {\expandafter\etb@listitem@i
     \expandafter{\@secondoftwo#2}{#1}}}
\long\def\etb@listitem@i#1#2{#2{#1}}
\makeatother
\usepackage{biblatex}
```
Update on the way to CTAN now.

**Comment by pitkling** [comment]
Great, thanks for the quick fix!

**Comment by ArthurPreuss** [comment]
Sorry, but I am very new to LaTeX and I am trying to fix this problem as well.
Would it be possible to tell me please where should I insert the code that fixes the bug?
Thanks in advance!

**Comment by josephwright** [comment]
@ArthurPreuss It is fixed in the release version: if you have an up-to-date TeX system you'll have the fix (and if you have an older system you are likely not to need it).
