### ISSUE TITLE
macro test: version with full expansion of the macro

### ISSUE THREAD

**Issue by maieul** [josephwright/etoolbox#2]
Hi, actually, macro like `\ifdefvoid` don't expand there first argument before the test.

I think it could be nice to have some version of these macro which fully expands them.

See the MWE

```
\documentclass{article}
\usepackage{etoolbox}
\begin{document}
\ifdefvoid{\foo}{yes}{no}
\let\foo\relax
\ifdefvoid{\foo}{yes}{no}
\def\foo{\relax}
\ifdefvoid{\foo}{yes}{no}
\def\foo{\relax}
\expandafter\ifdefvoid\expandafter{\foo}{yes}{no}%Create a command to short this syntax

\end{document}
```

**Comment by josephwright** [comment]
There are two things here. First, your example shows one expansion but one might imagine the case

```
\def\foo{\relax}
\def\baz{\foo}
\ifdefvoid{\baz}{\TRUE}{\FALSE}
```

which would still give `FALSE`. It's not clear to me what the result of your proposed test would be here.

Second, `\ifdefvoid` works if the first argument is undefined. Any (partially) expanding definition would have to test for that first, then do expansion, making the logic more tricky. It also raises the question of what the outcome would be for a hypothetical

```
\def\foo{\undefine}
\ifedefvoid{\baz}{\TRUE}{\FALSE}
```

Can you suggest some real-world use cases for the syntax you are after?

**Comment by maieul** [comment]
My question is only for the expansion of the first argument, because the second and the last are always expanded after the test. My problem is only about "what is tested".

In the case of 

```
\def\foo{\undefine}
\ifedefvoid{\baz}{\TRUE}{\FALSE}
```

the outcome should be `\TRUE`. 

A real world example was a bug in eledmac http://tex.stackexchange.com/q/232714/7712. It was concerning a bad use of `\fcsempty` rather than `\ifdefvoid` but as I said in my question it was for macro like `\ifdefvoid`. I was thinking at all macro which test macro content.

The problem was I tested a macro which value was `\symplinenum` (https://github.com/maieul/ledmac/blob/d0edbe454118546507eae362e8b4ff1619d80d87/eledmac.dtx#L9679) . The default value of `\symplinenum` was nothing (https://github.com/maieul/ledmac/blob/d0edbe454118546507eae362e8b4ff1619d80d87/eledmac.dtx#L10052). So my test for  `ifcsempty`  returned false and not true (because I called the bad test...). 

So the solution I used was to use the `xstring` package (https://github.com/maieul/ledmac/commit/d0edbe454118546507eae362e8b4ff1619d80d87), but I thinkg such feature should be provided by etoolbox.

**Comment by maieul** [comment]
ps : I was thinking indeed not for a full expansion, like in xstring, even in my MWE provided only partially expansion.

**Comment by josephwright** [comment]
The macros provided by `etoolbox` are all well-defined in terms of the nature of their argument and the fact that expansion does not take place. In the case of `\ifdefvoid`, the description of the behaviour is clear in the sense that it tests the control sequence given directly without expansion.

The case outlined seems to be about the result of applying `\edef` (or perhaps `\protected@edef`) to the control sequence. (Internally, `\IfStrEq` does an `\edef`.) That's not equivalent to a single expansion `\expandafter\ifdefvoid\expandafter{\foo}` and neither case is really something that `etoolbox` encourages: the programmer needs to know where expansion is required and the appropriate form.

**Comment by maieul** [comment]
I was thinking to something with fully expand. In xstring 
"all the arguments are fully expanded (an \edef is used) before the the macro works on them. In most of the cases, this expansion mode avoids chains of \expandafter and allows lighter code.".

I was thinking of some similar test directly inside the etoolbox. The develloper will know where the argument will be fully expanded and when not : (s)he will choose

ps : In the MWE I provide that I provide with the expandafter, it was similar because my command could be expanded only one time. However, I agree it was not strictly identioc.
