### ISSUE TITLE
\DeclareListParser no longer accepts an empty

### ISSUE THREAD

**Issue by eg9** [josephwright/etoolbox#20]
The minimal example

```latex
\documentclass{article} 
\usepackage{etoolbox}

\DeclareListParser{\foo}{}

\begin{document} 
\end{document}
```

hangs in an infinite loop, because the empty second argument causes `\noexpand` in the definition to apply to the next `\noexpand`, so the delimiter quark is expanded. The same is for `\DeclareListParser*`.

The empty second argument is used in `cnltx-base.sty` and dependent packages.

```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./etoolboxbug.tex
LaTeX2e <2017-04-15>
Babel <3.17> and hyphenation patterns for 84 language(s) loaded.
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/local/texlive/2017/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2017/texmf-dist/tex/latex/etoolbox/etoolbox.sty)^C
! Interruption.
\etb@defparser@do ...d #2\noexpand \etb@lst@q@end 
                                                  \noexpand #2&}\long \csdef...
l.4 \DeclareListParser{\foo}{}
                              
?
```

The bug has been introduced with version 2.5b and is the same with version 2.5c

**Comment by josephwright** [comment]
Arguably the behaviour here is undefined, but I can adjust easily using `\unexpanded` so I will.

**Comment by eg9** [comment]
I'm not sure why `cnltx-base` does that definition for a parser with no delimiter, but, as this breaks other packages, having it fixed was necessary.

**Comment by josephwright** [comment]
See also #21
