### ISSUE TITLE
Why \etb@ifdefempty uses \ifstrempty, but not \ifx#1\@empty?

### ISSUE THREAD

**Issue by muzimuzhi** [josephwright/etoolbox#23]
Currently, `\etb@ifdefempty{control sequence}` uses `\ifstrempty` internally (see [etoolbox.sty#L275-L280](https://github.com/josephwright/etoolbox/blob/302a6c7b10b16c2bb5874e229807319e3e70f952/etoolbox.sty#L275-L280)). But in kernel of latex2e, the scheme `\ifx{<control sequence>}\@empty ... \else ... \fi` is commonly used to test if a control sequence is empty.

Are there any benefits the `etoolbox` way has?

**Comment by josephwright** [comment]
The `\ifx` test has to have _exactly_ equivalent definitions. In particular, if you test with a `\long` or `\protected` macro it give the unexpected result:
```latex
\def\testa{}
\long\def\testb{}
\protected\def\testc{}
\ifx\testa\empty\TRUE\else\FALSE\fi
\ifx\testb\empty\TRUE\else\FALSE\fi
\ifx\testc\empty\TRUE\else\FALSE\fi
```
For the purposes of `etoolbox`, it's the net outcome that's important: the result of using the macro is 'nothing'.

**Comment by muzimuzhi** [comment]
Thanks for your explanation.
