### ISSUE TITLE
csnumdef reset in whileboolexpr loop?

### ISSUE THREAD

**Issue by rHermes** [josephwright/etoolbox#24]
I'm playing around with the etoolbox package and I'm trying to generate a table.

http://pastebin.tlhiv.org/5Slmu1AZ

Here is the code in question. The problem is the \csnumdef part. If I change that to
csnumgdef it works, and produces correctly, but now it only runs for the first iteration of the inner loop.

I can't seem to figure out what I'm doing wrong, I'm not even sure this is a bug, but there is so little 
example code out there that I've just reported it here.

**Comment by rHermes** [comment]
It seems that you cannot have an ifnumless inbetween the csnumdef and the usage of it. I don't know why this would be, but here is the working draft: http://pastebin.tlhiv.org/6l9YDNpl and in code

```latex
\documentclass{article}

\usepackage{etoolbox}

\begin{document}
\begin{table}[h]
  \centering
\newcounter{FontI}
\newcounter{FontJ}[FontI]
\newcounter{FontK}
\begin{tabular}{r | c c c c c c c c c c}
  % Header
  \whileboolexpr{test {\ifnumless{\value{FontK}}{10} }}{& \theFontK \stepcounter{FontK}} \\ \hline
  % Loop
  \whileboolexpr{
  test { \ifnumless{\value{FontI}}{13} }
  }{
    % inside j
  \ifnumgreater{\value{FontI}}{0}{\theFontI{}}{}x%
  \whileboolexpr{%
  test { \ifnumless{\value{FontJ}}{10} }
  }{% only put behind on not first.
  %\ifnumgreater{\value{FontJ}}{0}{& }{}%
  & \csnumdef{lol}{\value{FontI}*10 + \value{FontJ}}%
  \ifnumless{\csuse{lol}}{128}{\texttt{\symbol{\csuse{lol}}}}{ }%
                                    \stepcounter{FontJ}}%
                                    \stepcounter{FontI}%
  \ifnumless{\value{FontI}}{13}{\\}{}
  }%
\end{tabular}
\caption{Table of the symbols from 0 to 127. Inspired by Math Into \LaTeX}
\end{table}
\end{document}

```

**Comment by josephwright** [comment]
Can you post a minimal example which shows the issue? I'm not sure I totally follow.

**Comment by rHermes** [comment]
It seems that the site I used to host it on cleared the pastebin :( Stupid of me to rely on that.

I will try to reproduce the example for you and post the source code here! Sorry for making such a mess of this.

**Comment by rHermes** [comment]
Ok, I managed to reproduce it!

So here is a minimal example of what doesn't work:

```latex
\documentclass{standalone}

\usepackage{etoolbox}

\begin{document}

\newcounter{I}
\newcounter{J}[I]
\begin{tabular}{c c c}
  % first loop
  \whileboolexpr{test {\ifnumless{\value{I}}{5}}}{
  \ifnumgreater{\value{I}}{0}{\\}{}%
  % second loop
  \whileboolexpr{test {\ifnumless{\value{J}}{3}}}{
  % define number
  \csnumdef{pain}{\value{I}*3 + \value{J}}%
  % check if we should have &
  \ifnumgreater{\value{J}}{0}{&}{}%
  % use the number
  [ \csuse{pain} ]%
  % Step the counter
  \stepcounter{J} %
  }%
  \stepcounter{I}
  }
\end{tabular}

\end{document}
```
![image](https://user-images.githubusercontent.com/5375290/47210576-9ba90a00-d393-11e8-9c25-7637fa372665.png)

However, if I move the csnumdef to after the ifnumgreater line it works:
```latex
\documentclass{standalone}

\usepackage{etoolbox}

\begin{document}

\newcounter{I}
\newcounter{J}[I]
\begin{tabular}{c c c}
  % first loop
  \whileboolexpr{test {\ifnumless{\value{I}}{5}}}{
  \ifnumgreater{\value{I}}{0}{\\}{}%
  % second loop
  \whileboolexpr{test {\ifnumless{\value{J}}{3}}}{
  % check if we should have &
  \ifnumgreater{\value{J}}{0}{&}{}%
  % define number
  \csnumdef{pain}{\value{I}*3 + \value{J}}%
  % use the number
  [ \csuse{pain} ]%
  % Step the counter
  \stepcounter{J} %
  }%
  \stepcounter{I}
  }
\end{tabular}

\end{document}
```
![image](https://user-images.githubusercontent.com/5375290/47210634-c2674080-d393-11e8-9ec7-27d74f1b85ea.png)

The same happens if I use csnumgdef, it will then work. This is why I am suspecting that this is because
of a scoping issue. This might just be intended behavior, I am too new to LaTeX to know if it is or not.

Hopefully this is much clearer than the initial report!

**Comment by josephwright** [comment]
Table cells form groups at a TeX level: you are in a different group with a local definition, so the behaviour is 'expected' (as in `etoolbox` is not misbehaving).
