### ISSUE TITLE
\multicolumn fails with "! Misplaced \omit" in a macro test branch

### ISSUE THREAD

**Issue by jotbeel** [josephwright/etoolbox#36]
Here is the MWE:

\documentclass{minimal}
\usepackage{etoolbox}
\def\bar{bar}
\begin{document}
\begin{tabular}{l}
\ifcsstring{\bar}{bar}	
	{\multicolumn{1}{l}{bar}\\\\}
	{not bar\\\\}
\end{tabular}
\end{document}

**Comment by josephwright** [comment]
TeX only allows the underlying `\omit` at the start of a cell, and there can be no non-expandable content before that. The way `\ifcsstring` works is non-expandable, so this simply cannot work.

**Comment by jotbeel** [comment]
Silly/naive me... 
Perhaps those non-expandable could be marked as such in the manual? With \ifcsdef{\bar} the MWE works, thus it's expandable :-)

Thank you, Joseph.  Closing.
