### ISSUE TITLE
\NewCommandCopy with \endminipage

### ISSUE THREAD

**Issue by bdtc** [josephwright/etoolbox#41]
```
\documentclass{article}

\usepackage{etoolbox}

\NewCommandCopy{\mytest}{\endminipage}

\begin{document}
Some text.
\end{document}
```
`! Paragraph ended before \etb@carsquare was complete.`

The above works fine without etoolbox.

The above also works fine with etoolbox and most other environments.

**Comment by muzimuzhi** [comment]
A mis-spelling in issue title: `\NewCopyCommand` should be `\NewCommandCopy`.

**Comment by muzimuzhi** [comment]
Duplicate of #35. Already fixed but not released yet.

btw There's a mis-spelling in issue title: `\NewCopyCommand` should be `\NewCommandCopy`.

**Comment by bdtc** [comment]
Edited the title.
