### ISSUE TITLE
csname version of \NewCommandCopy, etc.

### ISSUE THREAD

**Issue by bdtc** [josephwright/etoolbox#42]
Consider adding `\csNewCommandCopycs` and related.  These can be done with the proper mix of `\NewCommandCopy` with `\expandafter`, of course, but it is a little tricky to figure out, especially to copy an environment with its end macro.

**Comment by muzimuzhi** [comment]
An opportunity to provide aliased user commands for latex3 functions `\exp_args:Nc` and its friends. Sounds like a proposal to the latex2e kernel.

**Comment by bdtc** [comment]
Edited the macro names.

**Comment by bdtc** [comment]
The etoolbox documentation was the natural place to look for this, due to it having the other cs-related macros.  I shall open a related issue with the latex2e project: [LaTeX2e github #735](https://github.com/latex3/latex2e/issues/735)

**Comment by josephwright** [comment]
This is being handled in the kernel.
