### ISSUE TITLE
\ifincsvlist

### ISSUE THREAD

**Issue by maieul** [josephwright/etoolbox#5]
etoolbox provides `\ifinlist` to test the present of an element in a internal list.

Should it be possible to add `\ifincsvlist` which will be equivalent for user input csv list.

**Comment by josephwright** [comment]
As with https://github.com/josephwright/etoolbox/issues/13, there is a problem here in that [`etextools`](http://ctan.org/pkg/etextools) also defines `\ifincsvlist`. I'm reluctant to make add any more clashes, so this one is likely to be a 'no' on that basis (have to decide what to do about `\listdel` as it is!).
