### ISSUE TITLE
convert cvs list to internal list

### ISSUE THREAD

**Issue by maieul** [josephwright/etoolbox#6]
Should it be possible to provides a tool which will convert a cvs list to an internal list?

**Comment by maieul** [comment]
notes that the handbook provides an example of such tools. But a generic command should be nice.

**Comment by josephwright** [comment]
As with https://github.com/josephwright/etoolbox/issues/13, there is a potential clash with [`etextools`](http://ctan.org/pkg/etextools) here: it has `\csvtolist`.
