### ISSUE TITLE
tool to manipulate TeX boxes

### ISSUE THREAD

**Issue by maieul** [josephwright/etoolbox#7]
`etoolbox` provide tool to manipulate TeX command, like `\csdef`.

Should not it useful to have such tool for boxes? I think to something like:
- `\newcsbox{boxname}`
- `\setcsbox{boxname}=something`

**Comment by josephwright** [comment]
I'm not sure this is (quite) in-scope. The package is about 'programming tools', and boxes are specifically _typesetting_ not _programming_. I need to think a bit about it: I'm wary of exceeding the original author's idea of the package aims.

**Comment by maieul** [comment]
I understand. But in my sense box are not only typeset tool: it us a data type in the TeX programming.
